clear; close all; drawnow

figure(3)
x = -5:.01:5;
beta = 0;
gam = 1;
delta = 0;
plot(x,  stbl.cdf(x,.1,beta,gam,delta),...
   x , stbl.cdf(x,.5,beta,gam,delta),...
   x , stbl.cdf(x,.75,beta,gam,delta),...
   x , stbl.cdf(x,1,beta,gam,delta),...
   x , stbl.cdf(x,1.25,beta,gam,delta),...
   x , stbl.cdf(x,1.5,beta,gam,delta) )
axis([-5 5 0 1]);
title('Symmetric \alpha-stable CDFs, \beta = 0, \gamma = 1, \delta = 0');
legend('\alpha = 0.1',...
   '\alpha = 0.5',...
   '\alpha = 0.75',...
   '\alpha = 1.0',...
   '\alpha = 1.25',...
   '\alpha = 1.5',...
   'Location','northwest');


figure(4)
x = -5:.01:5;
beta = .5;
gam = 1;
delta = 0;
quick = true;
plot( x,  stbl.cdf(x,.1,beta,gam,delta),...
   x , stbl.cdf(x,.5,beta,gam,delta),...
   x , stbl.cdf(x,.75,beta,gam,delta),...
   x , stbl.cdf(x,1,beta,gam,delta),...
   x , stbl.cdf(x,1.25,beta,gam,delta),...
   x , stbl.cdf(x,1.5,beta,gam,delta) )
axis([-5 5 0 1]);
title('Skewed \alpha-stable CDFs, \beta = 0.5, \gamma = 1, \delta = 0');
legend('\alpha = 0.1',...
   '\alpha = 0.5',...
   '\alpha = 0.75',...
   '\alpha = 1.0',...
   '\alpha = 1.25',...
   '\alpha = 1.5',...
   'Location','northwest');